name: Run Trading Bot Daily

on:
  schedule:
    - cron: '*/10 3-10 * * 1-5'
  workflow_dispatch: # Manual test button
  repository_dispatch: # 🔥 Yeh line bahar se auto-trigger karne ke liye hai
    types: [auto_trigger]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Libraries
      run: |
        pip install -r requirements.txt

    - name: Run Script
      run: python Parshwa87bot.py
